// <auto-generated />
namespace CarDealership.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedFNameAndLName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFNameAndLName));
        
        string IMigrationMetadata.Id
        {
            get { return "201804030256284_addedFNameAndLName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
